### ISSUE TITLE
Incompatibility FTB please fix

### ISSUE THREAD

**Issue by xXjojojXx** [Ladysnake/PlayerAbilityLib#22]
java.lang.RuntimeException: stacktrace
at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63) ~[pal-1.8.0.jar:?]
at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[pal-1.8.0.jar:?]
at net.minecraft.class_3222.handler$fpg000$playerabilitylib$checkAbilityConsistency(class_3222.java:22424) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_7355(class_3222.java:1323) ~[server-intermediary.jar:?]
at dev.ftb.mods.ftbessentials.FTBEEventHandler.lambda$playerTickPost$4(FTBEEventHandler.java:136) ~[ftb-essentials-fabric-2001.2.2.jar:?]
at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at dev.ftb.mods.ftbessentials.FTBEEventHandler.playerTickPost(FTBEEventHandler.java:126) ~[ftb-essentials-fabric-2001.2.2.jar:?]
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:731) ~[?:?]
at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-9.1.13-fabric.jar:?]
at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-9.1.13-fabric.jar:?]
at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-31.1-jre.jar:?]
at jdk.proxy2.$Proxy282.tick(Unknown Source) ~[?:?]
at net.minecraft.class_1657.handler$zlk000$architectury$postTick(class_1657.java:9409) ~[server-intermediary.jar:?]
at net.minecraft.class_1657.method_5773(class_1657.java:332) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.mixinextras$bridge$method_14226$218(class_3244.java) ~[server-intermediary.jar:?]
at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:63) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
at net.minecraft.class_3244.wrapOperation$fai000$neruina$catchTickingPlayer(class_3244.java:8454) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

The error ensures that all Gamemode home TPA commands are ineffective, so unfortunately this error occurs when you are in the Nether

**Comment by xXjojojXx** [comment]
[latest.log](https://github.com/Ladysnake/PlayerAbilityLib/files/14383833/latest.log)

**Comment by xXjojojXx** [comment]
It seems like there's an issue with the "Pal" mod causing a runtime exception. The exception occurs at line 63 in the PalInternals class and is related to checking conflicts with the ability tracker. The stack trace also shows involvement from other mods like "FTB Essentials" and "Neruina".

**Comment by Pyrofab** [comment]
This is a warning telling you that FTB is meddling with player abilities without coordinating with other mods. I can't do much about it, compatibility would have to be added on their side.
